apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: weave-scope
  namespace: weave
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: weave.imroc.io
    http:
      paths:
      - backend:
          serviceName: weave-scope-weave-scope
          servicePort: 80
        path: /
